<a href="https://colab.research.google.com/github/Ananya-AJ/Deep-Learning/blob/main/2b_operations_pytorch_individual.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [3]:
# Scalar vector multiplication

a = torch.rand(1)
b = torch.rand(8, 3)
mult = torch.einsum('i, ij -> ij', [a, b])
print(a)
print(b)
print(mult)

tensor([0.9527])
tensor([[0.9159, 0.5157, 0.5155],
        [0.0795, 0.0986, 0.4750],
        [0.7315, 0.0623, 0.7837],
        [0.1413, 0.4651, 0.4515],
        [0.7715, 0.9578, 0.0246],
        [0.7536, 0.7605, 0.0524],
        [0.8444, 0.9581, 0.2070],
        [0.9302, 0.8836, 0.7917]])
tensor([[0.8725, 0.4913, 0.4911],
        [0.0757, 0.0940, 0.4525],
        [0.6969, 0.0594, 0.7466],
        [0.1346, 0.4430, 0.4301],
        [0.7350, 0.9125, 0.0235],
        [0.7179, 0.7245, 0.0500],
        [0.8044, 0.9128, 0.1972],
        [0.8862, 0.8418, 0.7542]])


In [4]:
# Vector vector multiplication

a = torch.rand(3, 4)
b = torch.rand(4, 6)
mult = torch.einsum('ij, jk -> ik', [a, b])
print(a)
print(b)
print(mult)

tensor([[0.2097, 0.5419, 0.4652, 0.7254],
        [0.0995, 0.3792, 0.7318, 0.1850],
        [0.3614, 0.4519, 0.0195, 0.9595]])
tensor([[0.1836, 0.3458, 0.2365, 0.6283, 0.9129, 0.1729],
        [0.6768, 0.4992, 0.4833, 0.6024, 0.7941, 0.7571],
        [0.2811, 0.5799, 0.2425, 0.8327, 0.6434, 0.1461],
        [0.7048, 0.6511, 0.5994, 0.2550, 0.3839, 0.4551]])
tensor([[1.0472, 1.0851, 0.8591, 1.0305, 1.1995, 0.8446],
        [0.6109, 0.7685, 0.4951, 0.9474, 0.9338, 0.4954],
        [1.0539, 0.9866, 0.8837, 0.7602, 1.0696, 0.8442]])


In [5]:
# Outer product

a = torch.arange(4)
b = torch.arange(5, 6)  
prod = torch.einsum('i,j -> ij', [a, b])
print(a)
print(b)
print(prod)

tensor([0, 1, 2, 3])
tensor([5])
tensor([[ 0],
        [ 5],
        [10],
        [15]])


In [8]:
# Scalar dot product

a = torch.arange(9).reshape(3, 3)
b = torch.arange(6).reshape(3, 2)
prod = torch.einsum('ij, jk ->', [a, b])
print(a)
print(b)
print(prod)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 1],
        [2, 3],
        [4, 5]])
tensor(204)


In [9]:
# Hadamard product

a = torch.arange(8).reshape(2, 4)
b = torch.arange(4, 12).reshape(2, 4)
prod = torch.einsum('ij, ij -> ij', [a, b])
print(a)
print(b)
print(prod)

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  5, 12, 21],
        [32, 45, 60, 77]])


In [10]:
# Batch matrix multiplication

a = torch.randn(3, 3, 6)
b = torch.randn(3, 6, 2)
batch_mult = torch.einsum('bij, bjk -> bik', [a, b])
print(a)
print(b)
print(batch_mult)

tensor([[[-0.4792,  0.4405, -0.8789, -1.5049, -0.3394,  0.9293],
         [-1.1061, -1.4470,  0.2143, -0.7699,  0.9990, -1.4475],
         [-1.7678,  0.2661,  1.5959,  0.4693, -1.0327,  1.8573]],

        [[ 0.6898,  0.1513,  0.3559, -1.5186, -1.2020,  0.7653],
         [ 0.1598, -1.0463,  0.5399,  0.2603,  0.0208,  0.2813],
         [ 0.0309, -0.6352, -0.9038,  0.2339,  1.4732, -1.4333]],

        [[-1.5101,  0.8978,  0.3703, -0.4329, -2.0541,  1.9545],
         [-1.6846, -1.1632,  0.4950, -0.2574,  1.3567, -0.0393],
         [ 0.7013, -0.5347, -1.0344, -1.4109, -1.6172,  0.3820]]])
tensor([[[ 1.2306,  0.3978],
         [ 0.4323, -0.1920],
         [-1.0035, -0.6500],
         [ 0.4711,  0.3029],
         [-0.4294, -0.3311],
         [ 1.4648,  0.7701]],

        [[ 0.1334, -0.3789],
         [-0.3706,  0.7323],
         [-0.1679, -0.3407],
         [ 0.6593,  0.7570],
         [-0.1165, -0.3981],
         [ 0.2081,  1.0039]],

        [[ 0.3971,  0.0693],
         [ 0.5953, -1.9211],

In [11]:
# Tensor reduction

a = torch.randn(2, 3, 5, 7)
b = torch.randn(4, 1, 3, 11, 5)
reduction = torch.einsum('pqrs, tuqvr -> pstuv', [a, b])
print(a.shape, b.shape, reduction.shape)

torch.Size([2, 3, 5, 7]) torch.Size([4, 1, 3, 11, 5]) torch.Size([2, 7, 4, 1, 11])


In [13]:
# Transpose

a = torch.arange(8).reshape(2, 4)
transpose = torch.einsum('ij -> ji', [a])
print(a)
print(transpose)

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 4],
        [1, 5],
        [2, 6],
        [3, 7]])


In [14]:
# Bilinear transformation

a = torch.randn(2, 3)
b = torch.randn(3, 3, 4)
c = torch.randn(2, 4)
bilinear = torch.einsum('ik, jkl, il -> ij', [a, b, c])
print(a)
print(b)
print(c)
print(bilinear)

tensor([[-1.4101,  1.0852, -0.4636],
        [ 0.1006, -0.5854, -2.7060]])
tensor([[[ 0.3137, -0.4361, -0.3223, -0.3241],
         [-0.3332,  0.0225,  0.7285,  1.7542],
         [ 1.6624, -0.3904,  1.2754,  0.2033]],

        [[-1.6571, -0.4836,  0.1261,  1.7263],
         [-0.1359, -0.4000,  0.0607,  1.1899],
         [ 1.9795,  0.7114, -1.0291,  1.0837]],

        [[-1.1518, -0.1152,  0.9695,  0.2678],
         [-0.8789,  1.2201,  0.0176,  0.3097],
         [-1.0023, -0.8663,  0.5402, -0.3465]]])
tensor([[ 1.3945,  0.6184, -0.5007, -0.8351],
        [-0.1520,  0.5575,  1.5790, -0.3589]])
tensor([[-3.9085,  2.9139,  3.4512],
        [-4.3896,  5.4588, -2.0223]])


In [15]:
# Attention

def random_tensors(shape, num=1, requires_grad=False):
  tensors = [torch.randn(shape, requires_grad=requires_grad) for i in range(0, num)]
  return tensors[0] if num == 1 else tensors

# Parameters
# [hidden_dimension]
bM, br, w = random_tensors([7], num=3, requires_grad=True)
# [hidden_dimension x hidden_dimension]
WY, Wh, Wr, Wt = random_tensors([7, 7], num=4, requires_grad=True)

def attention(Y, ht, rt1):
  # [batch_size x hidden_dimension] 
  tmp = torch.einsum('ik, kl -> il', [ht, Wh]) + torch.einsum('ik, kl -> il', [rt1, Wr])

  Mt = torch.tanh(torch.einsum('ijk, kl -> ijl', [Y, WY]) + tmp.unsqueeze(1).expand_as(Y) + bM)
  
  # [batch_size x sequence_length]
  at = torch.nn.functional.softmax(torch.einsum('ijk, k -> ij', [Mt, w])) 
  
  # [batch_size x hidden_dimension]
  rt = torch.einsum('ijk, ij -> ik', [Y, at]) + torch.tanh(torch.einsum('ij, jk -> ik', [rt1, Wt]) + br)
  
  return rt, at

# Inputs - [batch_size x sequence_length x hidden_dimension]
Y = torch.randn(3,5,7)
# [batch_size x hidden_dimension]
ht, rt1 = random_tensors([3, 7], num=2)

rt, at = attention(Y, ht, rt1)

print(at)

tensor([[0.5012, 0.2671, 0.1465, 0.0302, 0.0550],
        [0.5457, 0.0989, 0.0013, 0.0011, 0.3529],
        [0.3610, 0.0948, 0.1997, 0.1840, 0.1605]], grad_fn=<SoftmaxBackward0>)


<ipython-input-15-0f495568e4dc>:20: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  at = torch.nn.functional.softmax(torch.einsum('ijk, k -> ij', [Mt, w]))


In [16]:
# Treeqn

def transition(zl):
  # [batch_size x num_actions x hidden_dimension]
  return zl.unsqueeze(1) + torch.tanh(torch.einsum('bk, aki -> bai', [zl, W]) + b)

# Inputs - [batch_size x hidden_dimension]
zl = torch.randn(2, 3)
# Parameters - [num_actions x hidden_dimension]
b = torch.randn(5, 3)
# Actions - [num_actions x hidden_dimension x hidden_dimension]
W = torch.randn(5, 3, 3)

transition(zl)

tensor([[[-1.5253,  0.3540,  0.1424],
         [-2.3261,  0.4054, -0.3410],
         [-0.4074,  0.5071,  0.1663],
         [-1.2789,  0.6472,  0.0891],
         [-2.2515,  0.6404, -1.0033]],

        [[-0.6477, -0.8759, -0.3058],
         [-0.6614, -2.5155, -0.0969],
         [-0.6276, -1.9070,  0.2905],
         [ 1.0452, -0.6064, -0.5417],
         [ 0.1474, -2.3005, -1.5779]]])