<a href="https://colab.research.google.com/github/Ananya-AJ/Deep-Learning/blob/main/2b_Operations_Tensorflow_individual_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
#import torch.nn.functional as F

In [2]:
# Scalar vector multiplication
a = tf.random.normal([1])
b = tf.random.normal([5, 6])
mult = tf.einsum('k, ij -> ij', a, b)
print(a)
print(b)
print(mult)

tf.Tensor([1.2821679], shape=(1,), dtype=float32)
tf.Tensor(
[[ 0.40165392  0.65783745 -2.111114    0.53767616  0.59892994 -1.9345528 ]
 [ 0.72670317 -1.9698162  -0.8262181   0.7928331  -1.5487446   1.0704191 ]
 [ 1.5264395  -0.57796836  0.75386935 -1.7936537  -0.62643427  0.23802334]
 [ 1.2598141   0.3106607   0.6674961  -0.13703941  1.605088   -0.13743961]
 [-0.46057248 -0.01992672  0.7327933  -0.28497723 -0.39194766  0.79076666]], shape=(5, 6), dtype=float32)
tf.Tensor(
[[ 0.51498777  0.84345806 -2.7068026   0.68939114  0.7679288  -2.4804215 ]
 [ 0.9317555  -2.5256352  -1.0593504   1.0165452  -1.9857506   1.372457  ]
 [ 1.9571518  -0.7410525   0.96658707 -2.2997653  -0.8031939   0.30518588]
 [ 1.6152933   0.39831915  0.85584205 -0.17570753  2.0579922  -0.17622066]
 [-0.59053123 -0.0255494   0.939564   -0.36538866 -0.50254273  1.0138956 ]], shape=(5, 6), dtype=float32)


In [6]:
# Vector vector multiplication

a = tf.random.normal([2, 7])
b = tf.random.normal([7, 3])
mult = tf.einsum('ij, jk -> ik', a, b)
print(a)
print(b)
print(mult)

tf.Tensor(
[[-0.41132474  0.91623765  0.77093697  1.5895838   2.0400152   2.3900526
   1.2411517 ]
 [-0.35397866 -0.05396651 -1.0702811   1.2171493   1.1295874  -2.8512108
  -1.3250433 ]], shape=(2, 7), dtype=float32)
tf.Tensor(
[[ 0.5471122  -0.43221912  0.11204296]
 [-0.14812954  0.24180292 -0.45709532]
 [-0.47763172 -0.16644199  1.4961685 ]
 [ 1.1308765   0.04805908 -0.01858621]
 [-0.02196163  0.4942314   0.6119839 ]
 [-0.22993766  0.3769104  -0.89048046]
 [-1.8391749   0.74487144 -0.47952586]], shape=(7, 3), dtype=float32)
tf.Tensor(
[[-1.808424   3.1809826 -0.8159898]
 [ 4.7697535 -1.1267786  2.2266932]], shape=(2, 3), dtype=float32)


In [7]:
# Outer product

a = tf.range(4)
b = tf.range(3, 8)  
prod = tf.einsum('i,j -> ij', a, b)
print(a)
print(b)
print(prod)

tf.Tensor([0 1 2 3], shape=(4,), dtype=int32)
tf.Tensor([3 4 5 6 7], shape=(5,), dtype=int32)
tf.Tensor(
[[ 0  0  0  0  0]
 [ 3  4  5  6  7]
 [ 6  8 10 12 14]
 [ 9 12 15 18 21]], shape=(4, 5), dtype=int32)


In [9]:
# Scalar dot product

a = tf.range(9)
a = tf.reshape(a, [3, 3])

b = tf.range(6)
b = tf.reshape(b, [3, 2])

prod = tf.einsum('ij, jk ->', a, b)
print(a)
print(b)
print(prod)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 1]
 [2 3]
 [4 5]], shape=(3, 2), dtype=int32)
tf.Tensor(204, shape=(), dtype=int32)


In [15]:
# Hadamard product
a = tf.range(8)
a = tf.reshape(a, [2, 4])

b = tf.range(4, 12)
b = tf.reshape(b, [2, 4])

prod = tf.einsum('ij, ij -> ij', a, b)
print(a)
print(b)
print(prod)
     

tf.Tensor(
[[0 1 2 3]
 [4 5 6 7]], shape=(2, 4), dtype=int32)
tf.Tensor(
[[ 4  5  6  7]
 [ 8  9 10 11]], shape=(2, 4), dtype=int32)
tf.Tensor(
[[ 0  5 12 21]
 [32 45 60 77]], shape=(2, 4), dtype=int32)


In [16]:
# Batch matrix multiplication

a = tf.random.normal([3, 4, 2])
b = tf.random.normal([3, 2, 2])
batch_mult = tf.einsum('bij, bjk -> bik', a, b)
print(a)
print(b)
print(batch_mult)

tf.Tensor(
[[[ 0.38194624  0.34270915]
  [-0.879425   -0.73935103]
  [-1.2717137  -1.3472259 ]
  [ 0.35558152  1.9951417 ]]

 [[ 1.3271325  -0.4018247 ]
  [-1.1578293  -0.8873949 ]
  [-1.5925052  -0.40281194]
  [-1.1819249  -0.2048785 ]]

 [[-0.99848324  0.05251945]
  [-0.46846178 -0.72392076]
  [-0.43762836 -0.11834554]
  [ 0.25437918  0.24476476]]], shape=(3, 4, 2), dtype=float32)
tf.Tensor(
[[[-1.2051611  -1.3100903 ]
  [ 0.8105676  -0.9133905 ]]

 [[-0.13709576 -0.20872512]
  [ 0.78235644 -0.21937971]]

 [[ 0.83996737 -0.15409812]
  [ 0.76714176 -0.77182287]]], shape=(3, 2, 2), dtype=float32)
tf.Tensor(
[[[-1.8251780e-01 -8.1341136e-01]
  [ 4.6055478e-01  1.8274424e+00]
  [ 4.4060230e-01  2.8966031e+00]
  [ 1.1886642e+00 -2.2881875e+00]]

 [[-4.9631441e-01 -1.8885370e-01]
  [-5.3552562e-01  4.3634450e-01]
  [-9.6816793e-02  4.2076463e-01]
  [ 1.7488897e-03  2.9164362e-01]]

 [[-7.9840344e-01  1.1332868e-01]
  [-9.4884241e-01  6.3092768e-01]
  [-4.5838133e-01  1.5877950e-01]
  [ 4.0

In [17]:
# Tensor reduction

a = tf.random.normal([2, 3, 5, 7])
b = tf.random.normal([4, 1, 3, 11, 5])
reduction = tf.einsum('pqrs, tuqvr -> pstuv', a, b)
print(a.shape, b.shape, reduction.shape)

(2, 3, 5, 7) (4, 1, 3, 11, 5) (2, 7, 4, 1, 11)


In [18]:
# Transpose

a = tf.range(8)
a = tf.reshape(a, [4, 2])
transpose = tf.einsum('ij -> ji', a)
print(a)
print(transpose)

tf.Tensor(
[[0 1]
 [2 3]
 [4 5]
 [6 7]], shape=(4, 2), dtype=int32)
tf.Tensor(
[[0 2 4 6]
 [1 3 5 7]], shape=(2, 4), dtype=int32)


In [19]:
# Bilinear transformation

a = tf.random.normal([2, 3])
b = tf.random.normal([3, 3, 4])
c = tf.random.normal([2, 4])
bilinear = tf.einsum('ik, jkl, il -> ij', a, b, c)
print(a)
print(b)
print(c)
print(bilinear)

tf.Tensor(
[[-0.9481942  -0.14559609  0.10019495]
 [-0.17483857  0.07601499  0.8096505 ]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[[-0.6213212  -2.9392493   1.3732809  -1.0760288 ]
  [ 0.4968914   0.09411446 -0.02515964  1.0737703 ]
  [ 1.2254181  -0.7105061  -0.50872606  0.11953892]]

 [[ 0.20993432 -1.1688963   0.1455556   0.30529317]
  [ 0.1548564  -0.07812924 -1.531444   -0.5993297 ]
  [-0.8454384  -0.03670199  0.47082785 -1.2650276 ]]

 [[ 0.07656003  0.9501785   0.2355877   0.9915011 ]
  [-0.22254634 -0.22615905 -0.6547773  -0.8297342 ]
  [-0.88420963 -0.285777   -0.2397389  -1.1546401 ]]], shape=(3, 3, 4), dtype=float32)
tf.Tensor(
[[-0.7159194  -0.57833844 -0.33297968  0.6554019 ]
 [-0.86000353 -1.760971   -0.8747508   0.6627217 ]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[-0.9971797  -0.6857547   0.0485958 ]
 [-0.06878227 -0.6406889   0.84514046]], shape=(2, 3), dtype=float32)


In [20]:
# Attention

# Parameters
# [hidden_dimension]
bM = tf.random.normal([7])
br = tf.random.normal([7]) 
w = tf.random.normal([7])
# [hidden_dimension x hidden_dimension]
WY = tf.random.normal([7, 7])
Wh = tf.random.normal([7, 7])
Wr = tf.random.normal([7, 7])
Wt = tf.random.normal([7, 7])

def attention(Y, ht, rt1):
  # [batch_size x hidden_dimension] 
  tmp = tf.einsum('ik, kl -> il', ht, Wh) + tf.einsum('ik, kl -> il', rt1, Wr)

  tmp_expanded = tf.expand_dims(tmp, 1)
  tmp_tiled = tf.tile(tmp_expanded, [1, Y.shape[1], 1]) 
  Mt = tf.tanh(tf.einsum('ijk, kl -> ijl', Y, WY) + tmp_tiled + bM)
  
  # [batch_size x sequence_length]
  at = tf.nn.softmax(tf.einsum('ijk, k -> ij', Mt, w)) 
  
  # [batch_size x hidden_dimension]
  rt = tf.einsum('ijk, ij -> ik', Y, at) + tf.tanh(tf.einsum('ij, jk -> ik', rt1, Wt) + br)
  
  return rt, at

# Inputs - [batch_size x sequence_length x hidden_dimension]
Y = tf.random.normal([3,5,7])
# [batch_size x hidden_dimension]
ht = tf.random.normal([3, 7])
rt1 = tf.random.normal([3, 7])

rt, at = attention(Y, ht, rt1)

print(at)

tf.Tensor(
[[0.475607   0.03602824 0.03254459 0.02391376 0.4319064 ]
 [0.11185419 0.5547139  0.05950851 0.09914203 0.17478135]
 [0.44022503 0.02524615 0.00213021 0.18614516 0.3462534 ]], shape=(3, 5), dtype=float32)


In [21]:
# Treeqn

def transition(zl):
  # [batch_size x num_actions x hidden_dimension]
  return tf.expand_dims(zl, 1) + tf.tanh(tf.einsum('bk, aki -> bai', zl, W) + b)

# Inputs - [batch_size x hidden_dimension]
zl = tf.random.normal([2, 3])
# Parameters - [num_actions x hidden_dimension]
b = tf.random.normal([5, 3])
# Actions - [num_actions x hidden_dimension x hidden_dimension]
W = tf.random.normal([5, 3, 3])

transition(zl)

<tf.Tensor: shape=(2, 5, 3), dtype=float32, numpy=
array([[[ 0.04611313, -1.5458914 ,  0.15339035],
        [ 1.8910638 ,  0.39829463, -0.25270396],
        [ 1.8700469 , -0.19741261, -0.7094743 ],
        [ 1.8402438 ,  0.4028399 , -1.6650093 ],
        [ 1.3817077 , -0.31313896,  0.14207983]],

       [[-0.3804952 ,  0.54636776, -0.5358778 ],
        [-2.074747  ,  0.5418301 , -0.5695238 ],
        [-1.4495701 ,  0.65666157,  1.4124969 ],
        [-0.3395161 ,  0.7817504 ,  1.3766361 ],
        [-2.0388396 ,  0.5666682 , -0.5710226 ]]], dtype=float32)>