<a href="https://colab.research.google.com/github/Ananya-AJ/Deep-Learning/blob/main/2b_operations_numpy_individual.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
# Scalar vector multiplication

a = np.array([3])
b = np.array([2, 5, 5])
mult = np.einsum('i, i -> i', a, b)
print(a)
print(b)
print(mult)

[3]
[2 5 5]
[ 6 15 15]


In [4]:
# Vector vector multiplication

a = np.random.randn(2, 6)
b = np.random.randn(6, 3)
mult = np.einsum('ij, jk -> ik', a, b)
print(a)
print(b)
print(mult)

[[-0.72859947 -0.56311665 -0.35044626 -0.30744911 -0.99209694  2.39079482]
 [-1.02041021 -1.26305752 -0.77954606  0.87423459 -2.09409991  1.3987705 ]]
[[ 0.85130973 -0.74018118  0.38085159]
 [-1.44091758  0.52099845  0.06960448]
 [ 0.39815797  1.55230256 -0.46172546]
 [-0.06153631  0.26717691  0.59367007]
 [-0.13053762  0.64004958 -0.0941532 ]
 [-0.70043374  0.35689859  0.96035181]]
[[-1.4745602  -0.16194914  2.05201616]
 [-0.11929024 -1.72038717  1.94288186]]


In [5]:
# Outer product

a = np.arange(1, 5)
b = np.arange(3, 7)  
prod = np.einsum('i,j -> ij', a, b)
print(a)
print(b)
print(prod)

[1 2 3 4]
[3 4 5 6]
[[ 3  4  5  6]
 [ 6  8 10 12]
 [ 9 12 15 18]
 [12 16 20 24]]


In [7]:
# Scalar dot product

a = np.arange(12).reshape(4, 3)
b = np.arange(6).reshape(3, 2)
prod = np.einsum('ij, jk ->', a, b)
print(a)
print(b)
print(prod)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[0 1]
 [2 3]
 [4 5]]
362


In [10]:
# Hadamard product

a = np.arange(8).reshape(2, 4)
b = np.arange(4, 12).reshape(2, 4)
prod = np.einsum('ij, ij -> ij', a, b)
print(a)
print(b)
print(prod)

[[0 1 2 3]
 [4 5 6 7]]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  5 12 21]
 [32 45 60 77]]


In [12]:
# Batch matrix multiplication

a = np.random.randn(3, 3, 2)
b = np.random.randn(3, 2, 4)
batch_mult = np.einsum('bij, bjk -> bik', a, b)
print(a)
print(b)
print(batch_mult)

[[[-0.31962483  1.4148762 ]
  [ 0.20404965 -0.22198179]
  [-0.37749063 -0.22708498]]

 [[-1.08374724 -0.44933437]
  [ 1.06290236 -0.29772882]
  [ 0.4378594  -0.31263385]]

 [[ 1.29628121 -0.59295881]
  [-0.12298078 -1.3757131 ]
  [ 1.23526394 -0.72507427]]]
[[[ 0.05380001 -0.10710565  0.58741396  0.00387171]
  [ 1.31363412 -0.25281405  0.8619768  -1.23723948]]

 [[-1.61076337  0.30450433 -0.49622679 -1.4899322 ]
  [ 1.04003193 -0.06713588 -0.71787845  0.38075592]]

 [[-0.81878825 -0.55689415 -0.76793029 -0.1727706 ]
  [-0.02897642 -1.16214546  1.35274138  0.15814141]]]
[[[ 1.84143383 -0.32346696  1.03183836 -1.75177819]
  [-0.28062497  0.03426524 -0.07148153  0.27543465]
  [-0.31861558  0.09784165 -0.41748525  0.27949697]]

 [[ 1.27833827 -0.29983927  0.86035187  1.44362319]
  [-2.02173168  0.34364665 -0.31370752 -1.69701447]
  [-1.03043707  0.15431903  0.00715554 -0.77141801]]

 [[-1.044198   -0.03278703 -1.79757353 -0.31773063]
  [ 0.14055846  1.66726601 -1.76654337 -0.19630974]
  [-

In [13]:
# Tensor reduction

a = np.random.randn(2, 3, 5, 7)
b = np.random.randn(4, 1, 3, 11, 5)
reduction = np.einsum('pqrs, tuqvr -> pstuv', a, b)
print(a.shape, b.shape, reduction.shape)

(2, 3, 5, 7) (4, 1, 3, 11, 5) (2, 7, 4, 1, 11)


In [14]:
# Transpose

a = np.arange(12).reshape(3, 4)
transpose = np.einsum('ij -> ji', a)
print(a)
print(transpose)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [15]:
# Bilinear transformation

a = np.random.randn(2, 3)
b = np.random.randn(3, 3, 4)
c = np.random.randn(2, 4)
bilinear = np.einsum('ik, jkl, il -> ij', a, b, c)
print(a)
print(b)
print(c)
print(bilinear)

[[ 1.33851164  0.50644219  1.27982596]
 [-0.05272189 -1.89758596  1.91693229]]
[[[-1.26932736 -0.34576171 -1.14349446 -0.72750098]
  [ 1.92434282  0.66681852 -0.90064607 -0.43727088]
  [-0.27326683 -0.46046469  0.13461986 -1.48669756]]

 [[ 1.5308133   0.21304475 -0.27943283 -0.242511  ]
  [ 0.19862012 -1.19262243 -0.16951406  0.28193146]
  [ 0.16772231  0.16115379 -0.41408051  0.61597856]]

 [[-1.16101544  1.00004474  0.51856689  1.21406435]
  [ 0.9486985   0.73723797  0.28176153  0.24247397]
  [-0.10885383 -0.23344128 -0.23053203  1.24669335]]]
[[ 0.14825699  1.32885782 -1.85326231 -0.09412653]
 [-1.3730545  -0.82481975  0.75127308  1.70308882]]
[[ 2.5455755   1.97822504  0.37936051]
 [ 5.54589239 -1.14730375  6.66401468]]


In [16]:
# Attention

# Parameters
# [hidden_dimension]
bM = np.random.randn(7)
br = np.random.randn(7) 
w = np.random.randn(7)
# [hidden_dimension x hidden_dimension]
WY = np.random.randn(7, 7)
Wh = np.random.randn(7, 7)
Wr = np.random.randn(7, 7)
Wt = np.random.randn(7, 7)

def attention(Y, ht, rt1):
  # [batch_size x hidden_dimension] 
  tmp = np.einsum('ik, kl -> il', ht, Wh) + np.einsum('ik, kl -> il', rt1, Wr)

  tmp_expanded = np.expand_dims(tmp, 1)
  tmp_tiled = np.tile(tmp_expanded, [1, Y.shape[1], 1]) 
  Mt = np.tanh(np.einsum('ijk, kl -> ijl', Y, WY) + tmp_tiled + bM)
  
  # [batch_size x sequence_length]
  at = np.einsum('ijk, k -> ij', Mt, w)
  at = np.exp(at)/np.sum(np.exp(at))
  
  # [batch_size x hidden_dimension]
  rt = np.einsum('ijk, ij -> ik', Y, at) + np.tanh(np.einsum('ij, jk -> ik', rt1, Wt) + br)
  
  return rt, at

# Inputs - [batch_size x sequence_length x hidden_dimension]
Y = np.random.randn(3,5,7)
# [batch_size x hidden_dimension]
ht = np.random.randn(3, 7)
rt1 = np.random.randn(3, 7)

rt, at = attention(Y, ht, rt1)

print(at)

[[0.01010618 0.04288619 0.21485085 0.14605524 0.04786392]
 [0.11552635 0.00181341 0.04861536 0.109196   0.04144443]
 [0.04740241 0.02643523 0.01030841 0.06427336 0.07322265]]


In [17]:
# Treeqn

def transition(zl):
  # [batch_size x num_actions x hidden_dimension]
  return np.expand_dims(zl, 1) + np.tanh(np.einsum('bk, aki -> bai', zl, W) + b)

# Inputs - [batch_size x hidden_dimension]
zl = np.random.rand(2, 3)
# Parameters - [num_actions x hidden_dimension]
b = np.random.rand(5, 3)
# Actions - [num_actions x hidden_dimension x hidden_dimension]
W = np.random.rand(5, 3, 3)

transition(zl)

array([[[0.40404847, 1.02994525, 1.09285103],
        [0.89218362, 1.05390802, 0.80343065],
        [0.90450645, 0.87865806, 1.00905008],
        [0.73507678, 1.00492581, 0.96942851],
        [0.96203947, 0.95220603, 1.01723394]],

       [[0.94274188, 1.60727937, 1.40107505],
        [1.28734255, 1.58125909, 1.21205071],
        [1.26744136, 1.48996276, 1.27671707],
        [1.19326402, 1.5540381 , 1.30871214],
        [1.32289484, 1.59260185, 1.42297863]]])